services:
  auth-mysql:
    container_name: auth-mysql
    hostname: auth-mysql
    restart: unless-stopped
    image: mysql:8.3
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
      # - ./initialize_database.sql:/docker-entrypoint-initdb.d/initialize_database.sql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - default

  auth-service:
    container_name: auth-service
    hostname: auth-service
    build: .
    restart: unless-stopped
    depends_on:
      - auth-mysql
    ports:
      - "8007:8007"
    env_file:
      - .env
    environment:
      - DB_HOST=auth-mysql
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8007 --reload
    networks:
      - default

networks:
  default:
