apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  DB_HOST: host.minikube.internal
  DB_PORT: "3306"
  DB_USER: root
  FASTAPI_HOST: "0.0.0.0"
  FASTAPI_PORT: "8000"
  RABBITMQ_USERNAME: finyed
