apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  CURRENT_ENV: development
  DB_HOST: mysql-service
  DB_NAME: auth
  DB_PORT: "3306"
  DB_USER: root
  AUTH_SVC_HOST: "0.0.0.0"
  AUTH_SVC_PORT: "8007"
  STRIPE_CONFIG_FILE: "./stripeconfig.json"
