apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  CURRENT_ENV: development
  DB_HOST: mysql-service
  DB_NAME: auth
  DB_PORT: "3306"
  DB_USER: root
  FASTAPI_HOST: "0.0.0.0"
  FASTAPI_PORT: "8000"
  RABBITMQ_USERNAME: finyed
