name: Docker Image CI for GHCR

on:
  push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITOPS_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/auth-service:latest -t ghcr.io/${{ github.repository_owner }}/auth-service:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/auth-service:latest
          docker push ghcr.io/${{ github.repository_owner }}/auth-service:${{ github.sha }}

  update-gitops:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v3
        with:
          repository: lukasdrothler/k8s-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: finyed/overlays/dev

      - name: Update Image Tag
        run: |
          # Navigate to the directory containing kustomization.yaml
          cd finyed/overlays/dev
          
          # Update the image tag using kustomize
          kustomize edit set image ghcr.io/lukasdrothler/auth-service=ghcr.io/lukasdrothler/auth-service:${{ github.sha }}

      - name: Commit and Push Changes
        run: |
          cd finyed/overlays/dev
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes before committing
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "update: auth-service image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit"
          fi